import AVKit
import SwiftUI

// MARK: - Demo Video Library

/// Maps exercise names (lowercased, fuzzy-matched) to bundled demo videos.
/// Videos are generated by scripts/exercise-video-pipeline/ and bundled
/// into the app under Resources/Videos/.
enum DemoVideoLibrary {

    /// Look up a demo video for the given exercise name. Returns nil when
    /// no bundled video exists for it.
    static func videoURL(for exerciseName: String) -> URL? {
        let slug = Self.slug(for: exerciseName)
        return Bundle.main.url(forResource: slug, withExtension: "mp4")
    }

    /// Fuzzy-match an exercise name to a bundled video slug.
    private static func slug(for exerciseName: String) -> String? {
        let name = exerciseName.lowercased()

        // Direct slug hits
        if name.contains("curl") && !name.contains("dumbbell") && !name.contains("ez") { return "barbell-curl" }
        if name.contains("ez") && name.contains("curl") { return "ez-curl" }
        if name.contains("squat") { return "back-squat" }
        if name.contains("bench") && name.contains("press") { return "bench-press" }
        if name.contains("deadlift") && !name.contains("romanian") { return "deadlift" }
        if name.contains("trap") || name.contains("hex") { return "trap-bar-deadlift" }
        if name.contains("overhead") || name.contains("shoulder press") { return "overhead-press" }
        if name.contains("romanian") { return "romanian-deadlift" }

        // Category fallbacks: a straight Olympic barbell curl works for most
        // bicep-focused barbell exercises. Extend as more videos are added.
        if name.contains("bicep") { return "barbell-curl" }
        if name.contains("tricep pushdown") { return nil }
        if name.contains("row") { return nil }
        if name.contains("lunge") { return nil }

        return nil
    }
}

// MARK: - Looping Demo Video Player

/// Auto-playing, looping, muted inline video player for exercise demos.
/// Falls back to a provided gradient placeholder when no video exists.
struct DemoVideoPlayer: View {
    let url: URL?
    var height: CGFloat = 200
    var fallbackGradient: [Color]

    @State private var player: AVPlayer?

    var body: some View {
        Group {
            if let url {
                VideoPlayer(player: player ?? AVPlayer(url: url))
                    .disabled(true)
                    .frame(height: height)
                    .clipShape(RoundedRectangle(cornerRadius: BFRadius.card, style: .continuous))
                    .onAppear {
                        if player == nil {
                            player = AVPlayer(url: url)
                            player?.isMuted = true
                            player?.play()

                            // Loop the short rep video seamlessly.
                            NotificationCenter.default.addObserver(
                                forName: .AVPlayerItemDidPlayToEndTime,
                                object: player?.currentItem,
                                queue: .main
                            ) { _ in
                                player?.seek(to: .zero)
                                player?.play()
                            }
                        }
                    }
                    .onDisappear {
                        player?.pause()
                        player = nil
                    }
            } else {
                // No bundled video for this exercise — keep the old gradient.
                ZStack {
                    RoundedRectangle(cornerRadius: BFRadius.card, style: .continuous)
                        .fill(
                            LinearGradient(
                                colors: fallbackGradient,
                                startPoint: .topLeading,
                                endPoint: .bottomTrailing
                            )
                        )
                        .frame(height: height)

                    VStack(spacing: 12) {
                        Image(systemName: "play.circle.fill")
                            .font(.system(size: 56))
                            .foregroundStyle(.white.opacity(0.9))

                        Text("Demo Video")
                            .font(BFTypography.subheadlineEmphasis)
                            .foregroundStyle(.white.opacity(0.8))
                    }
                }
            }
        }
    }
}