name: BetterFit
options:
  bundleIdPrefix: dev.echohello
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"

packages:
  BetterFit:
    path: ../..

targets:
  BetterFitApp:
    type: application
    platform: iOS
    sources:
      - path: BetterFitApp
        excludes:
          - "**/*.md"
    resources:
      - path: BetterFitApp/Assets.xcassets
      - path: BetterFitApp/Fonts
        excludes:
          - "**/*.md"
    info:
      path: BetterFitApp/Info.plist
      properties:
        CFBundleDisplayName: BetterFit
        UILaunchScreen: {}
        UIAppFonts:
          - BBHHegarty-Regular.ttf
          - BBHHegarty-Italic.ttf
          - BBHHegarty-Bold.ttf
          - BBHHegarty-BoldItalic.ttf
          - BBHHegarty-ExtraBold.ttf
          - BBHHegarty-ExtraBoldItalic.ttf
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: ""
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.echohello.BetterFit
        SWIFT_VERSION: "5.0"
        CODE_SIGN_ENTITLEMENTS: BetterFitApp/BetterFitApp.entitlements
      configs:
        Debug:
          CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
    capabilities:
      healthKit: true
    dependencies:
      - package: BetterFit

  BetterFitDev:
    type: application
    platform: iOS
    sources:
      - path: BetterFitApp
        excludes:
          - "**/*.md"
    resources:
      - path: BetterFitApp/Assets.xcassets
      - path: BetterFitApp/Fonts
        excludes:
          - "**/*.md"
    info:
      path: BetterFitApp/Info.plist
      properties:
        CFBundleDisplayName: BetterFit Dev
        UILaunchScreen: {}
        UIAppFonts:
          - BBHHegarty-Regular.ttf
          - BBHHegarty-Italic.ttf
          - BBHHegarty-Bold.ttf
          - BBHHegarty-BoldItalic.ttf
          - BBHHegarty-ExtraBold.ttf
          - BBHHegarty-ExtraBoldItalic.ttf
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: ""
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.echohello.BetterFit.dev
        SWIFT_VERSION: "5.0"
        CODE_SIGN_ENTITLEMENTS: BetterFitApp/BetterFitApp.entitlements
      configs:
        Debug:
          CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
    capabilities:
      healthKit: true
    dependencies:
      - package: BetterFit

  BetterFitWatch:
    type: application
    platform: watchOS
    sources:
      - path: BetterFitWatchApp
    resources:
      - path: BetterFitWatchApp/Assets.xcassets
      - path: BetterFitApp/Fonts
        excludes:
          - "**/*.md"
    info:
      path: BetterFitWatchApp/Info.plist
      properties:
        CFBundleDisplayName: BetterFit
        WKApplication: true
        WKWatchOnly: true
        UIAppFonts:
          - BBHHegarty-Regular.ttf
          - BBHHegarty-Italic.ttf
          - BBHHegarty-Bold.ttf
          - BBHHegarty-BoldItalic.ttf
          - BBHHegarty-ExtraBold.ttf
          - BBHHegarty-ExtraBoldItalic.ttf
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.echohello.BetterFit.watchkitapp
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "4"
        WATCHOS_DEPLOYMENT_TARGET: "10.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SKIP_INSTALL: NO
    dependencies:
      - package: BetterFit

schemes:
  BetterFit:
    build:
      targets:
        BetterFitApp: all
    run:
      config: Debug
  BetterFitDev:
    build:
      targets:
        BetterFitDev: all
    run:
      config: Debug
  BetterFitWatch:
    build:
      targets:
        BetterFitWatch: all
    run:
      config: Debug
